spring:
  cloud:
    config:
      enabled: true
      uri: http://localhost:8081
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:service_affiliationdata
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop
    show-sql: true

server:
  port: 8003
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    hostname: localhost