server:
  port: 8081

spring:
  cloud:
    config:
      server:
        git:
          default-label: main
          uri: https://github.com/pscalderonm/msoft-commercial-api-project
          search-paths: config-data
  application:
    name: config-service