server:
  port: 8081

spring:
  cloud:
    config:
      server:
        git:
          default-label: auth-service
          uri: https://github.com/bvegaM/microservices-example-users
          search-paths: config-data
  application:
    name: config-service